
title: Blog
url: 'http://yldrmzffr.github.io'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Muzaffer Yıldırım
tagline: Software Developer
pic: https://avatars0.githubusercontent.com/u/22274025?v=3&s=140

#sidebar links
email: yldrmzffr@gmail.com
phone: 
website: http://yldrmzffr.github.io
linkedin: yldrmzffr
github: yldrmzffr
twitter: '@yldrmzffr'

